## Randn Play

In [1]:
import torch

# Create a tensor of shape (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor)

# Use view() to reshape the tensor to shape (3, 2)
reshaped_tensor = tensor.view(3, 2)
print(reshaped_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [2]:
reshaped_tensor = tensor.view(-1)
print(reshaped_tensor)

tensor([1, 2, 3, 4, 5, 6])


In [3]:
reshaped_tensor = tensor.view(1)
print(reshaped_tensor)

RuntimeError: shape '[1]' is invalid for input of size 6

When you use `tensor.view(-1)`, you're asking PyTorch to give you a tensor that has the same total number of elements `(6)`, but with a single dimension. The result will be a tensor of shape `(6,)`.

However, when you use `tensor.view(1)`, you're asking PyTorch to reshape the tensor to have a size of `1` along the first dimension.

In [5]:
reshaped_tensor = tensor.view(1, 6)
print(reshaped_tensor)

tensor([[1, 2, 3, 4, 5, 6]])
